### GET Consultant Access Token
POST http://localhost:8000/api/token/
accept: application/json
X-CSRFTOKEN: 9Z20Gl2SYVLX616MK5e4RyUDqRBUpdSK4BvBvqUNmGOmKLcT9C0xymyaUklx1jJH
Content-Type: application/json

{
  "username": "consultant_100_1",
  "password": "password123"
}

### Get Branch Admin Access token
POST http://localhost:8000/api/token/
accept: application/json
X-CSRFTOKEN: 9Z20Gl2SYVLX616MK5e4RyUDqRBUpdSK4BvBvqUNmGOmKLcT9C0xymyaUklx1jJH
Content-Type: application/json

{
  "username": "branch_106@a.com",
  "password": "password123"
}

### Get Main Admin Access token
POST http://main.immigrate.localhost:8000/api/token/
accept: application/json
X-CSRFTOKEN: 9Z20Gl2SYVLX616MK5e4RyUDqRBUpdSK4BvBvqUNmGOmKLcT9C0xymyaUklx1jJH
Content-Type: application/json

{
  "username": "admin@main.com",
  "password": "admin123"
}

### Get Demo Admin Access token
POST http://demo.immigrate.localhost:8000/api/token/
accept: application/json
X-CSRFTOKEN: 9Z20Gl2SYVLX616MK5e4RyUDqRBUpdSK4BvBvqUNmGOmKLcT9C0xymyaUklx1jJH
Content-Type: application/json

{
  "username": "admin@demo.com",
  "password": "demo123"
}

### Get Acme Admin Access token
POST https://acme-immigrate.logiclucent.in/api/token/
accept: application/json
#X-CSRFTOKEN: 9Z20Gl2SYVLX616MK5e4RyUDqRBUpdSK4BvBvqUNmGOmKLcT9C0xymyaUklx1jJH
Content-Type: application/json

{
  "username": "admin@acme.com",
  "password": "acme@123"
}

###