"""
ClientActivity model for timeline and audit trail.

This model tracks all significant client activities for timeline display and audit purposes.
Activities are immutable once created (no updates/deletes).
"""

from django.db import models


class ClientActivity(models.Model):
    """
    Timeline and audit trail for client activities.
    
    Tracks all significant actions performed on a client including:
    - Notes added/edited/deleted
    - Stage changes
    - Client assignments
    - Document uploads
    - Application creations
    - Task updates
    
    Activities are immutable - no updates or deletes after creation.
    
    Fields:
        client: Foreign key to Client (CASCADE delete)
        activity_type: Type of activity (choices enum)
        performed_by: Foreign key to User who performed the activity (SET_NULL)
        description: Human-readable description of the activity
        metadata: JSON field for activity-specific data
        created_at: Auto-timestamp when activity was created
    
    Relationships:
        - Many-to-One with Client (client.activities)
        - Many-to-One with User (performed_by.activities_performed)
    
    Indexes:
        - (client, created_at) for timeline queries
        - (client, activity_type) for filtered queries
        - (performed_by, created_at) for user activity tracking
    
    Usage:
        activity = ClientActivity.objects.create(
            client=client,
            activity_type='NOTE_ADDED',
            performed_by=request.user,
            description=f"Added note: {note.content[:50]}...",
            metadata={'note_id': note.id}
        )
    """
    
    # Activity type choices
    NOTE_ADDED = 'NOTE_ADDED'
    NOTE_EDITED = 'NOTE_EDITED'
    NOTE_DELETED = 'NOTE_DELETED'
    STAGE_CHANGED = 'STAGE_CHANGED'
    ASSIGNED = 'ASSIGNED'
    PROFILE_PICTURE_UPLOADED = 'PROFILE_PICTURE_UPLOADED'
    PASSPORT_UPDATED = 'PASSPORT_UPDATED'
    PROFICIENCY_ADDED = 'PROFICIENCY_ADDED'
    QUALIFICATION_ADDED = 'QUALIFICATION_ADDED'
    VISA_APPLICATION_CREATED = 'VISA_APPLICATION_CREATED'
    COLLEGE_APPLICATION_CREATED = 'COLLEGE_APPLICATION_CREATED'
    TASK_CREATED = 'TASK_CREATED'
    TASK_COMPLETED = 'TASK_COMPLETED'
    
    ACTIVITY_TYPE_CHOICES = [
        (NOTE_ADDED, 'Note Added'),
        (NOTE_EDITED, 'Note Edited'),
        (NOTE_DELETED, 'Note Deleted'),
        (STAGE_CHANGED, 'Stage Changed'),
        (ASSIGNED, 'Client Assigned'),
        (PROFILE_PICTURE_UPLOADED, 'Profile Picture Uploaded'),
        (PASSPORT_UPDATED, 'Passport Updated'),
        (PROFICIENCY_ADDED, 'Language Proficiency Added'),
        (QUALIFICATION_ADDED, 'Qualification Added'),
        (VISA_APPLICATION_CREATED, 'Visa Application Created'),
        (COLLEGE_APPLICATION_CREATED, 'College Application Created'),
        (TASK_CREATED, 'Task Created'),
        (TASK_COMPLETED, 'Task Completed'),
    ]
    
    client = models.ForeignKey(
        'immigration.Client',
        on_delete=models.CASCADE,
        related_name='activities',
        help_text="Client this activity relates to"
    )
    
    activity_type = models.CharField(
        max_length=30,
        choices=ACTIVITY_TYPE_CHOICES,
        help_text="Type of activity"
    )
    
    performed_by = models.ForeignKey(
        'immigration.User',
        on_delete=models.SET_NULL,
        null=True,
        related_name='activities_performed',
        help_text="User who performed the activity"
    )
    
    description = models.TextField(
        help_text="Human-readable description of the activity"
    )
    
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Activity-specific metadata (JSON object)"
    )
    
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when activity occurred"
    )
    
    class Meta:
        db_table = 'immigration_clientactivity'
        verbose_name = 'Client Activity'
        verbose_name_plural = 'Client Activities'
        ordering = ['-created_at']  # Newest first by default
        indexes = [
            models.Index(fields=['client', '-created_at'], name='ca_client_created_idx'),
            models.Index(fields=['client', 'activity_type'], name='ca_client_type_idx'),
            models.Index(fields=['performed_by', '-created_at'], name='ca_user_created_idx'),
        ]
    
    def __str__(self):
        # get_activity_type_display() is auto-generated by Django for choice fields
        return f"{self.get_activity_type_display()} for {self.client} by {self.performed_by} at {self.created_at}"  # type: ignore
    
    def save(self, *args, **kwargs):
        """
        Override save to prevent updates after creation (immutable records).
        Only allow creation, not updates.
        """
        if self.pk is not None:
            # Record already exists - prevent updates
            raise ValueError("ClientActivity records are immutable and cannot be updated")
        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        """
        Override delete to prevent deletion (immutable records).
        Activities are audit trail - they should never be deleted.
        """
        raise ValueError("ClientActivity records are immutable and cannot be deleted")
