# Generated by Django 4.2.6 on 2025-12-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='visa_application_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLIENT_ASSIGNED', 'Client Assigned'), ('APPLICATION_ASSIGNED', 'Application Assigned'), ('VISA_APPLICATION_ASSIGNED', 'Visa Application Assigned'), ('REMINDER_DUE', 'Reminder Due'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_DUE_SOON', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', help_text='Type of notification', max_length=30),
        ),
    ]
