# Generated by Django 4.2.6 on 2025-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was soft-deleted', null=True),
        ),
    ]
