# Generated by Django 4.2.6 on 2025-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0002_agent_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('SUPER_AGENT', 'Super Agent'), ('SUB_AGENT', 'Sub Agent')], default='SUB_AGENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_type'], name='immigration_agent_t_a8eea3_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['email'], name='immigration_email_6ced7c_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['deleted_at'], name='immigration_deleted_833392_idx'),
        ),
        migrations.AlterModelTable(
            name='agent',
            table='immigration_agent',
        ),
    ]
