# Generated by Django 4.2.6 on 2025-12-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0003_alter_agent_options_alter_agent_agent_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('title', models.CharField(help_text='Task title/summary', max_length=200)),
                ('detail', models.TextField(help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Task priority level', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='PENDING', help_text='Current task status', max_length=15)),
                ('due_date', models.DateTimeField(help_text='When the task should be completed')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for categorization (e.g., ['client_meeting', 'urgent'])")),
                ('comments', models.JSONField(blank=True, default=list, help_text='Comments and updates on the task')),
                ('client_id', models.IntegerField(blank=True, help_text='Related client ID', null=True)),
                ('visa_application_id', models.IntegerField(blank=True, help_text='Related visa application ID', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
            ],
            options={
                'db_table': 'immigration_task',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='application',
            name='client',
        ),
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='application',
            name='location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sub_agent',
        ),
        migrations.RemoveField(
            model_name='application',
            name='super_agent',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='applicationstage',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='applicationstage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='applicationstage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='clienthistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='course',
            name='broad_field',
        ),
        migrations.RemoveField(
            model_name='course',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='narrow_field',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='client',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='instituteintake',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='institutelocation',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='narrowfield',
            name='broad_field',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='client',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visaapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visacategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Visa Categories'},
        ),
        migrations.AlterModelOptions(
            name='visatype',
            options={'ordering': ['visa_category', 'name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='visacategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visacategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visacategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='visacategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='immigration_fee',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='immigration_fee_currency',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='sub_class',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='visa_service_fee',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='visa_service_fee_currency',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch managing this client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='immigration.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', help_text='Notification message content'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_DUE_SOON', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('VISA_APPROVED', 'Visa Approved'), ('VISA_REJECTED', 'Visa Rejected'), ('VISA_STATUS_UPDATE', 'Visa Status Update'), ('CLIENT_ASSIGNED', 'Client Assigned'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', help_text='Type of notification', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When user read this notification', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', help_text='Notification title', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visacategory',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visacategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visatype',
            name='code',
            field=models.CharField(blank=True, help_text='Official visa code/subclass', max_length=50),
        ),
        migrations.AddField(
            model_name='visatype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visatype',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether client is actively being serviced'),
        ),
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Referring agent (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to='immigration.agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Consultant assigned to this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was soft-deleted', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Referral source', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='stage',
            field=models.CharField(blank=True, choices=[('LE', 'Lead'), ('FU', 'Follow Up'), ('CT', 'Client'), ('CL', 'Close')], help_text='Current stage in client workflow', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='visa_category',
            field=models.ForeignKey(blank=True, help_text='Primary visa category of interest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_clients', to='immigration.visacategory'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User this notification is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Relevant date (task due date, visa expiry, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the related action has been completed'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='meta_info',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (task_id, client_id, etc.)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, help_text='Whether user has read this notification'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Consultant handling this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visa_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='client',
            field=models.ForeignKey(help_text='Client submitting this visa application', on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to='immigration.client'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_applied',
            field=models.DateField(blank=True, help_text='Date application was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_granted',
            field=models.DateField(blank=True, help_text='Date visa was granted', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_opened',
            field=models.DateField(blank=True, help_text='Date case was opened by immigration', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_rejected',
            field=models.DateField(blank=True, help_text='Date visa was rejected', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_withdrawn',
            field=models.DateField(blank=True, help_text='Date application was withdrawn', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dependent',
            field=models.BooleanField(default=False, help_text='Whether this is a dependent application'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Visa expiry date (if granted)', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='final_date',
            field=models.DateField(blank=True, help_text='Date of final decision', null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='immigration_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Government immigration fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='Required documents checklist from VisaType'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='service_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Agency service fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='transaction_reference_no',
            field=models.CharField(blank=True, help_text='Official government reference number', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_type',
            field=models.ForeignKey(help_text='Type of visa being applied for', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='immigration.visatype'),
        ),
        migrations.AlterField(
            model_name='visacategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of required documents for this visa type'),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='visa_category',
            field=models.ForeignKey(help_text='Parent visa category', on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='immigration.visacategory'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['branch', 'active'], name='immigration_branch__abd31e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['branch', 'stage'], name='immigration_branch__d5ed24_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='immigration_email_651a44_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['deleted_at'], name='immigration_deleted_826bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['assigned_to', 'read'], name='immigration_assigne_ff7878_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['assigned_to', 'created_at'], name='immigration_assigne_560daa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='immigration_notific_e27d04_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['due_date'], name='immigration_due_dat_e2ce68_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read'], name='immigration_read_a518ea_idx'),
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['client', 'status'], name='immigration_client__cb7484_idx'),
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['assigned_to'], name='immigration_assigne_40353e_idx'),
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['status', 'date_applied'], name='immigration_status_890272_idx'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='immigration_client',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='immigration_notification',
        ),
        migrations.AlterModelTable(
            name='visaapplication',
            table='immigration_visaapplication',
        ),
        migrations.AlterModelTable(
            name='visacategory',
            table='immigration_visacategory',
        ),
        migrations.AlterModelTable(
            name='visatype',
            table='immigration_visatype',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationStage',
        ),
        migrations.DeleteModel(
            name='ApplicationType',
        ),
        migrations.DeleteModel(
            name='BroadField',
        ),
        migrations.DeleteModel(
            name='ClientHistory',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseLevel',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='InstituteIntake',
        ),
        migrations.DeleteModel(
            name='InstituteLocation',
        ),
        migrations.DeleteModel(
            name='LPE',
        ),
        migrations.DeleteModel(
            name='NarrowField',
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
        migrations.DeleteModel(
            name='Proficiency',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(help_text='User this task is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='immigration_assigne_473f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'due_date'], name='immigration_assigne_3e812b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='immigration_status_7dce2c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='immigration_priorit_e9b9af_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='immigration_due_dat_7fc226_idx'),
        ),
    ]
