# Generated by Django 4.2.6 on 2025-12-29 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0003_make_task_assigned_to_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this task is assigned to (optional, mutually exclusive with assigned_to)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_tasks', to='immigration.branch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLIENT_ASSIGNED', 'Client Assigned'), ('APPLICATION_ASSIGNED', 'Application Assigned'), ('VISA_APPLICATION_ASSIGNED', 'Visa Application Assigned'), ('REMINDER_DUE', 'Reminder Due'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_DUE_SOON', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('TASK_MENTIONED', 'Task Mentioned'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', help_text='Type of notification', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User this task is assigned to (optional, mutually exclusive with branch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['branch', 'status'], name='immigration_branch__b2b096_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assigned_to__isnull', False), ('branch__isnull', True)), models.Q(('assigned_to__isnull', True), ('branch__isnull', False)), models.Q(('assigned_to__isnull', True), ('branch__isnull', True)), _connector='OR'), name='task_assignment_constraint'),
        ),
    ]
