# Generated by Django 4.2.27 on 2025-12-31 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0004_add_task_branch_assignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadfield",
            options={
                "ordering": ["name"],
                "verbose_name": "broad field",
                "verbose_name_plural": "broad fields",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["institute", "name"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AlterModelOptions(
            name="courselevel",
            options={
                "ordering": ["name"],
                "verbose_name": "course level",
                "verbose_name_plural": "course levels",
            },
        ),
        migrations.AlterModelOptions(
            name="institute",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "institute",
                "verbose_name_plural": "institutes",
            },
        ),
        migrations.AlterModelOptions(
            name="institutecontactperson",
            options={
                "ordering": ["name"],
                "verbose_name": "institute contact person",
                "verbose_name_plural": "institute contact persons",
            },
        ),
        migrations.AlterModelOptions(
            name="instituteintake",
            options={
                "ordering": ["-intake_date"],
                "verbose_name": "institute intake",
                "verbose_name_plural": "institute intakes",
            },
        ),
        migrations.AlterModelOptions(
            name="institutelocation",
            options={
                "ordering": ["country", "state"],
                "verbose_name": "institute location",
                "verbose_name_plural": "institute locations",
            },
        ),
        migrations.AlterModelOptions(
            name="instituterequirement",
            options={
                "ordering": ["requirement_type", "title"],
                "verbose_name": "institute requirement",
                "verbose_name_plural": "institute requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="narrowfield",
            options={
                "ordering": ["broad_field", "name"],
                "verbose_name": "narrow field",
                "verbose_name_plural": "narrow fields",
            },
        ),
        migrations.RemoveField(
            model_name="institute",
            name="restored_at",
        ),
        migrations.AddField(
            model_name="broadfield",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="broadfield",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="broadfield",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="broadfield",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="broadfield",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courselevel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courselevel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courselevel",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="courselevel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="courselevel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="institutecontactperson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutecontactperson",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="institutecontactperson",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institutecontactperson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="institutecontactperson",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instituteintake",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instituteintake",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instituteintake",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instituteintake",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="instituteintake",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="institutelocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutelocation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="institutelocation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institutelocation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="institutelocation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instituterequirement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instituterequirement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instituterequirement",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instituterequirement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="instituterequirement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="narrowfield",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="narrowfield",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="narrowfield",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="narrowfield",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="narrowfield",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="broadfield",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="broad_field",
            field=models.ForeignKey(
                help_text="Broad field of study",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="immigration.broadfield",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="coe_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Confirmation of Enrollment fee",
                max_digits=100,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="institute",
            field=models.ForeignKey(
                help_text="Institution offering this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="immigration.institute",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                help_text="Educational level of the course",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="immigration.courselevel",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="narrow_field",
            field=models.ForeignKey(
                help_text="Specific field of study",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="immigration.narrowfield",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total tuition fee for the course",
                max_digits=100,
            ),
        ),
        migrations.AlterField(
            model_name="courselevel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="institute",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when record was soft-deleted",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="name",
            field=models.CharField(
                help_text="Full name of the institution", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="short_name",
            field=models.CharField(help_text="Abbreviated name", max_length=20),
        ),
        migrations.AlterField(
            model_name="institutecontactperson",
            name="institute",
            field=models.ForeignKey(
                help_text="Institution this contact person belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_persons",
                to="immigration.institute",
            ),
        ),
        migrations.AlterField(
            model_name="institutecontactperson",
            name="position",
            field=models.CharField(
                blank=True, help_text="Job title or position", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="instituteintake",
            name="institute",
            field=models.ForeignKey(
                help_text="Institution this intake belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intakes",
                to="immigration.institute",
            ),
        ),
        migrations.AlterField(
            model_name="instituteintake",
            name="intake_date",
            field=models.DateField(help_text="Start date of this intake period"),
        ),
        migrations.AlterField(
            model_name="institutelocation",
            name="institute",
            field=models.ForeignKey(
                help_text="Institution this location belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="immigration.institute",
            ),
        ),
        migrations.AlterField(
            model_name="instituterequirement",
            name="institute",
            field=models.ForeignKey(
                help_text="Institution this requirement belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="immigration.institute",
            ),
        ),
        migrations.AlterField(
            model_name="narrowfield",
            name="broad_field",
            field=models.ForeignKey(
                help_text="Broad field this narrow field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="narrow_fields",
                to="immigration.broadfield",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="required_documents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Required documents checklist with received status. Format: [{'name': 'Document Name', 'received': bool}]",
            ),
        ),
        migrations.AddIndex(
            model_name="broadfield",
            index=models.Index(fields=["name"], name="immigration_name_e6121b_idx"),
        ),
        migrations.AddIndex(
            model_name="broadfield",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_a4768d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["institute"], name="immigration_institu_6f943c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["level"], name="immigration_level_i_00dbb2_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["broad_field"], name="immigration_broad_f_a7073c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["narrow_field"], name="immigration_narrow__6e5cda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["name"], name="immigration_name_797bd7_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_3c20ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courselevel",
            index=models.Index(fields=["name"], name="immigration_name_696dad_idx"),
        ),
        migrations.AddIndex(
            model_name="courselevel",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_f5d1f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institute",
            index=models.Index(fields=["name"], name="immigration_name_989757_idx"),
        ),
        migrations.AddIndex(
            model_name="institute",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_159c5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutecontactperson",
            index=models.Index(
                fields=["institute"], name="immigration_institu_599f18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutecontactperson",
            index=models.Index(fields=["email"], name="immigration_email_3d0544_idx"),
        ),
        migrations.AddIndex(
            model_name="institutecontactperson",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_d186ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instituteintake",
            index=models.Index(
                fields=["institute"], name="immigration_institu_15b7fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instituteintake",
            index=models.Index(
                fields=["intake_date"], name="immigration_intake__26f0b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instituteintake",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_87530b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutelocation",
            index=models.Index(
                fields=["institute"], name="immigration_institu_eb0fd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutelocation",
            index=models.Index(
                fields=["country"], name="immigration_country_f7808b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutelocation",
            index=models.Index(fields=["state"], name="immigration_state_71fa60_idx"),
        ),
        migrations.AddIndex(
            model_name="institutelocation",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_0db689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instituterequirement",
            index=models.Index(
                fields=["institute"], name="immigration_institu_57c9e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instituterequirement",
            index=models.Index(
                fields=["requirement_type"], name="immigration_require_98c733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instituterequirement",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_597de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="narrowfield",
            index=models.Index(
                fields=["broad_field"], name="immigration_broad_f_f02efa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="narrowfield",
            index=models.Index(fields=["name"], name="immigration_name_066fdd_idx"),
        ),
        migrations.AddIndex(
            model_name="narrowfield",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_af8a5c_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="broadfield",
            table="immigration_broad_field",
        ),
        migrations.AlterModelTable(
            name="course",
            table="immigration_course",
        ),
        migrations.AlterModelTable(
            name="courselevel",
            table="immigration_course_level",
        ),
        migrations.AlterModelTable(
            name="institute",
            table="immigration_institute",
        ),
        migrations.AlterModelTable(
            name="institutecontactperson",
            table="immigration_institute_contact_person",
        ),
        migrations.AlterModelTable(
            name="instituteintake",
            table="immigration_institute_intake",
        ),
        migrations.AlterModelTable(
            name="institutelocation",
            table="immigration_institute_location",
        ),
        migrations.AlterModelTable(
            name="instituterequirement",
            table="immigration_institute_requirement",
        ),
        migrations.AlterModelTable(
            name="narrowfield",
            table="immigration_narrow_field",
        ),
    ]
