# Generated by Django 4.2.27 on 2025-12-31 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0005_alter_broadfield_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Application type name (e.g., 'Undergraduate', 'Postgraduate')",
                        max_length=255,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                        ],
                        default="USD",
                        help_text="Default currency for fees and costs",
                        max_length=3,
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(
                        blank=True,
                        help_text="Tax label (e.g., 'GST', 'VAT', 'Sales Tax')",
                        max_length=100,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax percentage to apply (e.g., 10.00 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this application type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this application type is currently in use",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Type",
                "verbose_name_plural": "Application Types",
                "db_table": "immigration_applicationtype",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(help_text="Stage display name", max_length=100),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Display order (1-based, auto-managed)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what happens in this stage",
                    ),
                ),
                (
                    "application_type",
                    models.ForeignKey(
                        help_text="Parent application type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="immigration.applicationtype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "db_table": "immigration_stage",
                "ordering": ["application_type", "position"],
            },
        ),
        migrations.CreateModel(
            name="CollegeApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "finish_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected course completion date",
                        null=True,
                    ),
                ),
                (
                    "total_tuition_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total tuition fee for the course",
                        max_digits=12,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="Student ID assigned by institution (once enrolled)",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes and comments"
                    ),
                ),
                (
                    "application_type",
                    models.ForeignKey(
                        help_text="Type of application (determines workflow stages)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="college_applications",
                        to="immigration.applicationtype",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultant handling this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_college_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client submitting application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_applications",
                        to="immigration.client",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course being applied for (must belong to selected Institute)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="college_applications",
                        to="immigration.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        help_text="Educational institution",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="college_applications",
                        to="immigration.institute",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Campus location (must belong to selected Institute)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="college_applications",
                        to="immigration.institutelocation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Current workflow stage (auto-set to position 1 on create)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="college_applications",
                        to="immigration.stage",
                    ),
                ),
                (
                    "start_date",
                    models.ForeignKey(
                        help_text="Intake/start date (must belong to selected Institute)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="college_applications",
                        to="immigration.instituteintake",
                    ),
                ),
                (
                    "sub_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub agent (if applicable)",
                        limit_choices_to={"agent_type": "SUB_AGENT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_agent_college_applications",
                        to="immigration.agent",
                    ),
                ),
                (
                    "super_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Super agent (if applicable)",
                        limit_choices_to={"agent_type": "SUPER_AGENT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="super_agent_college_applications",
                        to="immigration.agent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "College Application",
                "verbose_name_plural": "College Applications",
                "db_table": "immigration_collegeapplication",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(
                fields=["application_type", "position"],
                name="immigration_applica_241094_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_c32745_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stage",
            unique_together={("application_type", "position")},
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(
                fields=["client", "stage"], name="immigration_client__a9623a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(
                fields=["application_type", "stage"],
                name="immigration_applica_f8d5ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(
                fields=["institute"], name="immigration_institu_026dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(
                fields=["start_date"], name="immigration_start_d_015184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(
                fields=["assigned_to"], name="immigration_assigne_0b5310_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(
                fields=["deleted_at"], name="immigration_deleted_d05e9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationtype",
            index=models.Index(fields=["title"], name="immigration_title_83a683_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationtype",
            index=models.Index(
                fields=["is_active", "deleted_at"],
                name="immigration_is_acti_d6df4e_idx",
            ),
        ),
    ]
