# Generated by Django 4.2.27 on 2026-01-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0006_applicationtype_stage_collegeapplication_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stage",
            name="immigration_deleted_c32745_idx",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="deleted_at",
        ),
    ]
