# Generated by Django 4.2.6 on 2025-12-09 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0006_client_profile_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='immigration_deleted_13954a_idx',
            old_name='immigration_branch_deleted_at_idx',
        ),
        migrations.RenameIndex(
            model_name='proficiency',
            new_name='immigration_client__838d06_idx',
            old_name='proficiency_client_test_date_idx',
        ),
        migrations.RenameIndex(
            model_name='proficiency',
            new_name='immigration_test_na_262de2_idx',
            old_name='proficiency_test_name_idx',
        ),
        migrations.RenameIndex(
            model_name='qualification',
            new_name='immigration_client__46ad78_idx',
            old_name='qualification_client_completion_idx',
        ),
        migrations.AlterField(
            model_name='lpe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpe',
            name='validity_term',
            field=models.PositiveSmallIntegerField(default=0, help_text='Validity window for results in years'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_DUE_SOON', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('VISA_APPROVED', 'Visa Approved'), ('VISA_REJECTED', 'Visa Rejected'), ('VISA_STATUS_UPDATE', 'Visa Status Update'), ('CLIENT_ASSIGNED', 'Client Assigned'), ('SYSTEM_ALERT', 'System Alert'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('APPLICATION_ASSIGNED', 'Application Assigned'), ('VISA_APPLICATION_ASSIGNED', 'Visa Application Assigned'), ('REMINDER', 'Reminder')], default='SYSTEM_ALERT', help_text='Type of notification', max_length=30),
        ),
        migrations.AlterField(
            model_name='passport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
