# Generated by Django 4.2.6 on 2025-12-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0007_sync_role_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Multiple branch assignments (used for BRANCH_ADMIN role)', related_name='branch_admins', to='immigration.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Multiple region assignments (used for REGION_MANAGER role)', related_name='region_managers', to='immigration.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Single branch assignment (used for CONSULTANT role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_single_branch', to='immigration.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Single region assignment (legacy field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_single_region', to='immigration.region'),
        ),
    ]
