# Generated by Django 4.2.27 on 2026-01-02 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0007_remove_stage_soft_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Event title/summary", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed event description"
                    ),
                ),
                ("start", models.DateTimeField(help_text="Event start date and time")),
                ("end", models.DateTimeField(help_text="Event end date and time")),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        editable=False,
                        help_text="Auto-calculated duration (end - start)",
                        null=True,
                    ),
                ),
                (
                    "hex_color",
                    models.CharField(
                        default="#3788d8",
                        help_text="Hex color code for calendar display (e.g., #FF5733)",
                        max_length=7,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Event location (physical or virtual)",
                        max_length=255,
                    ),
                ),
                (
                    "all_day",
                    models.BooleanField(
                        default=False, help_text="Whether this is an all-day event"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User this event is assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch this event is associated with (for multi-tenant scoping)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="immigration.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "immigration_calendar_event",
                "ordering": ["-start", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["assigned_to", "start"],
                        name="immigration_assigne_2b50fe_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "end"],
                        name="immigration_assigne_b6ed9d_idx",
                    ),
                    models.Index(
                        fields=["branch", "start"],
                        name="immigration_branch__364395_idx",
                    ),
                    models.Index(
                        fields=["start", "end"], name="immigration_start_2ccc86_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="immigration_deleted_543f9d_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="immigration_created_a34489_idx"
                    ),
                ],
            },
        ),
    ]
