# Generated by Django 4.2.6 on 2025-12-09 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0008_multi_tenant_role_updates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='immigration_tenant__077cf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='immigration_branch__a39a3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='immigration_region__0f9541_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branch assignments', related_name='assigned_users', to='immigration.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Region assignments', related_name='assigned_users', to='immigration.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='immigration.tenant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant'], name='immigration_tenant__3b964e_idx'),
        ),
    ]
