# Generated by Django 4.2.27 on 2026-01-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0008_calendarevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={
                "ordering": ["-start", "-created_at"],
                "permissions": [
                    ("view_team_events", "Can view team calendar events"),
                    (
                        "assign_calendarevent_to_others",
                        "Can assign calendar events to other users",
                    ),
                ],
            },
        ),
        migrations.RemoveIndex(
            model_name="calendarevent",
            name="immigration_deleted_543f9d_idx",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="deleted_at",
        ),
    ]
