# Generated by Django 4.2.6 on 2026-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0009_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
