# Generated by Django 4.2.6 on 2025-12-12 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import immigration.models.profile_picture


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0009_remove_role_field_use_groups_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stage',
            field=models.CharField(blank=True, choices=[('LEAD', 'Lead'), ('FOLLOW_UP', 'Follow Up'), ('CLIENT', 'Client'), ('CLOSE', 'Close')], help_text='Current stage in client workflow', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Profile picture file (JPEG, PNG, WebP, max 5MB)', upload_to=immigration.models.profile_picture.profile_picture_upload_path, validators=[immigration.models.profile_picture.validate_image_file])),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type (image/jpeg, image/png, image/webp)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when picture was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when picture was last updated')),
                ('client', models.OneToOneField(help_text='Client this picture belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='immigration.client')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_pictures_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Picture',
                'verbose_name_plural': 'Profile Pictures',
                'db_table': 'immigration_profilepicture',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Note content (max 10,000 characters)', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when note was last updated')),
                ('author', models.ForeignKey(help_text='User who created the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='immigration.client')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'immigration_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='note_client_created_idx'), models.Index(fields=['author', '-created_at'], name='note_author_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('NOTE_ADDED', 'Note Added'), ('NOTE_EDITED', 'Note Edited'), ('NOTE_DELETED', 'Note Deleted'), ('STAGE_CHANGED', 'Stage Changed'), ('ASSIGNED', 'Client Assigned'), ('PROFILE_PICTURE_UPLOADED', 'Profile Picture Uploaded'), ('PASSPORT_UPDATED', 'Passport Updated'), ('PROFICIENCY_ADDED', 'Language Proficiency Added'), ('QUALIFICATION_ADDED', 'Qualification Added'), ('VISA_APPLICATION_CREATED', 'Visa Application Created'), ('COLLEGE_APPLICATION_CREATED', 'College Application Created'), ('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed')], help_text='Type of activity', max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Activity-specific metadata (JSON object)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when activity occurred')),
                ('client', models.ForeignKey(help_text='Client this activity relates to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='immigration.client')),
                ('performed_by', models.ForeignKey(help_text='User who performed the activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Activity',
                'verbose_name_plural': 'Client Activities',
                'db_table': 'immigration_clientactivity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='ca_client_created_idx'), models.Index(fields=['client', 'activity_type'], name='ca_client_type_idx'), models.Index(fields=['performed_by', '-created_at'], name='ca_user_created_idx')],
            },
        ),
    ]
