# Generated by Django 4.2.6 on 2025-12-13 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('immigration', '0010_alter_client_stage_profilepicture_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, help_text='Optional time for the reminder', null=True)),
                ('meta_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('notification_created', models.BooleanField(default=False, help_text='Whether notification has been created for this reminder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reminder_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reminder_date', '-reminder_time'],
                'indexes': [models.Index(fields=['reminder_date', 'reminder_time', 'notification_created'], name='immigration_reminde_05b4bb_idx')],
            },
        ),
    ]
