# Generated by Django 4.2.6 on 2025-12-13 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_client_id_to_generic_fk(apps, schema_editor):
    """Migrate existing client_id data to generic FK (content_type, object_id)."""
    Task = apps.get_model('immigration', 'Task')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get ContentType for Client model
    try:
        client_content_type = ContentType.objects.get(app_label='immigration', model='client')
        
        # Migrate tasks with client_id to generic FK
        tasks_with_client = Task.objects.filter(client_id__isnull=False)
        for task in tasks_with_client:
            task.content_type = client_content_type
            task.object_id = task.client_id
            task.save(update_fields=['content_type', 'object_id'])
    except ContentType.DoesNotExist:
        # If Client model doesn't exist yet, skip migration
        pass


def reverse_migrate_generic_fk_to_client_id(apps, schema_editor):
    """Reverse migration: copy object_id back to client_id if content_type is Client."""
    Task = apps.get_model('immigration', 'Task')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        client_content_type = ContentType.objects.get(app_label='immigration', model='client')
        
        # Reverse migrate: copy object_id to client_id for Client content type
        tasks_with_client_link = Task.objects.filter(content_type=client_content_type)
        for task in tasks_with_client_link:
            task.client_id = task.object_id
            task.save(update_fields=['client_id'])
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('immigration', '0011_create_reminder_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of entity this task is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the entity this task is linked to', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='Related client ID (deprecated - use linked_entity instead)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='visa_application_id',
            field=models.IntegerField(blank=True, help_text='Related visa application ID (deprecated - use linked_entity instead)', null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['content_type', 'object_id'], name='immigration_content_04e77f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_by'], name='immigration_assigne_ed8321_idx'),
        ),
        # Data migration: migrate existing client_id to generic FK
        migrations.RunPython(migrate_client_id_to_generic_fk, reverse_migrate_generic_fk_to_client_id),
    ]
