# Generated by Django 4.2.6 on 2025-12-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0012_enhance_task_model'),
    ]

    operations = [
    ]
