# Generated by Django 4.2.27 on 2025-12-14 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0013_add_reminder_due_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("TASK_DUE_SOON", "Task Due Soon"),
                    ("TASK_OVERDUE", "Task Overdue"),
                    ("VISA_APPROVED", "Visa Approved"),
                    ("VISA_REJECTED", "Visa Rejected"),
                    ("VISA_STATUS_UPDATE", "Visa Status Update"),
                    ("CLIENT_ASSIGNED", "Client Assigned"),
                    ("REMINDER_DUE", "Reminder Due"),
                    ("SYSTEM_ALERT", "System Alert"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("APPLICATION_ASSIGNED", "Application Assigned"),
                    ("VISA_APPLICATION_ASSIGNED", "Visa Application Assigned"),
                    ("REMINDER", "Reminder"),
                ],
                default="SYSTEM_ALERT",
                help_text="Type of notification",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("employer_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employments",
                        to="immigration.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employment",
                "db_table": "immigration_employment",
                "ordering": ["-end_date", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["client", "end_date"],
                        name="immigration_client__5cea0e_idx",
                    )
                ],
            },
        ),
    ]
