# Generated by Django 4.2.27 on 2025-12-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0014_alter_notification_notification_type_employment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "broad field",
            },
        ),
        migrations.CreateModel(
            name="CourseLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "course level",
            },
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("website", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "institute",
            },
        ),
        migrations.CreateModel(
            name="NarrowField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "broad_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immigration.broadfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "narrow field",
            },
        ),
        migrations.CreateModel(
            name="InstituteRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic"),
                            ("LANGUAGE", "Language"),
                            ("FINANCIAL", "Financial"),
                            ("DOCUMENT", "Document"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="immigration.institute",
                    ),
                ),
            ],
            options={
                "verbose_name": "institute requirement",
                "verbose_name_plural": "institute requirements",
            },
        ),
        migrations.CreateModel(
            name="InstituteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_name", models.CharField(blank=True, max_length=100)),
                ("suburb", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immigration.institute",
                    ),
                ),
            ],
            options={
                "verbose_name": "institute location",
            },
        ),
        migrations.CreateModel(
            name="InstituteIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intake_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immigration.institute",
                    ),
                ),
            ],
            options={
                "verbose_name": "institute intake",
            },
        ),
        migrations.CreateModel(
            name="InstituteContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="immigration.institute",
                    ),
                ),
            ],
            options={
                "verbose_name": "institute contact person",
                "verbose_name_plural": "institute contact persons",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "total_tuition_fee",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("coe_fee", models.DecimalField(decimal_places=2, max_digits=100)),
                ("description", models.TextField(blank=True)),
                (
                    "broad_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="immigration.broadfield",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immigration.institute",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="immigration.courselevel",
                    ),
                ),
                (
                    "narrow_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="immigration.narrowfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
            },
        ),
    ]
